### ISSUE TITLE
Only component instances seem to be generated properly. Master Component is brought in as "background-image"

### ISSUE THREAD

**Issue by xetra11** [KlausSchaefers/figma-low-code#11]
It looks like the master component is not generated as real html element but as a screenshot.

![image](https://user-images.githubusercontent.com/8149023/95139121-0a8ff100-076c-11eb-80ba-c763b7f03e75.png)

**Component Instance HTML**
```html
<div class="qux-label qux-element qux-valign-top Ingumon_son_of_Albin_of_the_Boar_Warriors"><span class="qux-common-label">
    Ingumon son of Albin of the Boar Warriors 
  </span></div>
```
**Master Component HTML**
```html
<div class="qux-vector qux-element settler-component"></div>
```
**Master Component CSS**
```css
.Desktop_-_1 .settler-component {
    grid-column-start: 12;
    grid-column-end: 15;
    grid-row-start: 9;
    grid-row-end: 12;
    z-index: 19;
    height: 53px;
    width: 520px;
    background-image: url(https://s3-us-west-2.amazonaws.com/figma-alpha-api/img/dde2/eb04/ff998c0…);
}
```
